AppBundle\Entity\Cargo:
    type: entity
    table: cargo
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cargo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        abrev:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
