AppBundle\Entity\FrecuenciaInforme:
    type: entity
    table: frecuencia_informe
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        frecuenciaInforme:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: frecuencia_informe
    lifecycleCallbacks: {  }
