AppBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        IDX_2265B05D952BE730:
            columns:
                - empleado_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        usuario:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        estado:
            type: boolean
            nullable: true
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    manyToOne:
        empleado:
            targetEntity: Empleado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empleado_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
